### ISSUE TITLE
After 1.21.1 update asks for reinstall helper on every reboot

### ISSUE THREAD

**Issue by taylor325** [davidwernhart/AlDente-Charge-Limiter#910] opened 2023-03-12 04:59 UTC
After 1.21.1 update asks for reinstall helper on every reboot
M1 MacBook Pro, Ventura 13.2.1
AlDente Version: 1.21.1 (Free)
<img width="272" alt="Screenshot 2023-03-12 at 5 54 32" src="https://user-images.githubusercontent.com/52882397/224525271-6b66e969-9fe6-4ff2-9716-85da905c41b7.png">

**Comment by papas68** [comment] 2023-03-12 08:38
and the same thing happens to me


AlDente Pro Version: 1.21.1

**Comment by taylor325** [comment] 2023-03-12 15:05
Ok. I followed uninstallation guide [here](https://apphousekitchen.com/how-to-uninstall-aldente-pro/) and redownloaded AlDente from [here.](https://github.com/davidwernhart/AlDente-Charge-Limiter/releases/tag/1.21.1)
After 2 times reboot finally AlDente working normally.
I don't know if this solves the problem permanently, I need more testing.

**Comment by MatthiasKerbl** [comment] 2023-03-12 15:08
Hi everyone,

This issue seems to be caused by two potential reasons:

1. For some reason the helper application did not get updated and the new version of AlDente does not work with the old helper application.
2. More than one AlDente application file or installation on the system exists.

To fix these potential causes of this issue, please follow these steps:

- Open AlDente and go to Settings/General/Remove in the Helper Application section and remove the helper.
- Open the Finder and go to the Applications folder and delete the AlDente application file.
- If you have more AlDente application files anywhere else on your system, delete all of them as well.
- Go to finder and navigate to: /Library/PrivilegedHelperTools/ and delete the file: com.apphousekitchen.aldente-pro.helper if it is still there.
- Navigate to Library/LaunchDaemons/ next, and remove: com.apphousekitchen.aldente-pro.helper.plist if it is still there.
- Restart the MacBook
- Download and install the newest version of AlDente from here: https://github.com/davidwernhart/AlDente-Charge-Limiter/releases/download/1.21.1/AlDente.dmg
- Restart the MacBook to check if the bug is still happening.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment] 2023-03-12 15:25
Also, we already have a Github issue open for this bug here #866.
Therefore, I will close this issue and post updates on the other one.
Please also share now findings on the other issue.

Thanks,
Matthias

**Closed by MatthiasKerbl** 2023-03-12 15:25 UTC

**Comment by taylor325** [comment] 2023-03-12 22:07
After my computer power off and reboot still got this bug.
<img width="276" alt="Screenshot 2023-03-12 at 23 04 20" src="https://user-images.githubusercontent.com/52882397/224576566-b410875b-567c-4f59-bdc3-851f3c42c90a.png">

**Comment by taylor325** [comment] 2023-03-12 22:11
> Ok. I followed uninstallation guide [here](https://apphousekitchen.com/how-to-uninstall-aldente-pro/) and redownloaded AlDente from [here.](https://github.com/davidwernhart/AlDente-Charge-Limiter/releases/tag/1.21.1) After 2 times reboot finally AlDente working normally. I don't know if this solves the problem permanently, I need more testing.

After my computer power off and rebooted still got this bug.
I need install helper on every reboot. Weird! Never got this bug before AlDente 1.20.
<img width="276" alt="Screenshot 2023-03-12 at 23 04 20" src="https://user-images.githubusercontent.com/52882397/224576708-4c6d854a-45e0-4ed5-a070-b27111293089.png">

**Comment by papas68** [comment] 2023-03-13 07:41
I also get the same error

M1 MacBook Pro, Ventura 13.2.1
AlDente Pro Version: 1.21.1

**Comment by papas68** [comment] 2023-03-13 09:12
the same to me












| George ***@***.***  ....... |

 
 

    Στις Δευτέρα 13 Μαρτίου 2023 - 12:11:36 πμ EET, ο χρήστης taylor325 ***@***.***> έγραψε:  
 
 



Ok. I followed uninstallation guide here and redownloaded AlDente from here. After 2 times reboot finally AlDente working normally. I don't know if this solves the problem permanently, I need more testing.


After my computer power off and rebooted still got this bug.
I need install helper on every reboot. Weird! Never got this bug before AlDente 1.20.

**Comment by MatthiasKerbl** [comment] 2023-03-13 09:14
> the same to me | George ***@***.***  ....... |   Στις Δευτέρα 13 Μαρτίου 2023 - 12:11:36 πμ EET, ο χρήστης taylor325 ***@***.***> έγραψε: Ok. I followed uninstallation guide here and redownloaded AlDente from here. After 2 times reboot finally AlDente working normally. I don't know if this solves the problem permanently, I need more testing. After my computer power off and rebooted still got this bug. I need install helper on every reboot. Weird! Never got this bug before AlDente 1.20. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Hi @papas68,

Do I understand correctly that you could fix the issue as well?

**Comment by papas68** [comment] 2023-03-13 09:22
I have followed the instructions but the result is the same, it also reports the same taylor325














| George ***@***.***  ....... |

 
 

    Στις Δευτέρα 13 Μαρτίου 2023 - 11:14:51 πμ EET, ο χρήστης Matthias Kerbl ***@***.***> έγραψε:  
 
 



the same to me | George @.***  ....... |   Στις Δευτέρα 13 Μαρτίου 2023 - 12:11:36 πμ EET, ο χρήστης taylor325 @.> έγραψε: Ok. I followed uninstallation guide here and redownloaded AlDente from here. After 2 times reboot finally AlDente working normally. I don't know if this solves the problem permanently, I need more testing. After my computer power off and rebooted still got this bug. I need install helper on every reboot. Weird! Never got this bug before AlDente 1.20. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>


Hi @papas68,

Do I understand correctly that you could fix the issue as well?

**Comment by MatthiasKerbl** [comment] 2023-03-13 09:27
> I have followed the instructions but the result is the same, it also reports the same taylor325 | George ***@***.***  ....... |   Στις Δευτέρα 13 Μαρτίου 2023 - 11:14:51 πμ EET, ο χρήστης Matthias Kerbl ***@***.***> έγραψε: the same to me | George @.***  ....... |   Στις Δευτέρα 13 Μαρτίου 2023 - 12:11:36 πμ EET, ο χρήστης taylor325 @.> έγραψε: Ok. I followed uninstallation guide here and redownloaded AlDente from here. After 2 times reboot finally AlDente working normally. I don't know if this solves the problem permanently, I need more testing. After my computer power off and rebooted still got this bug. I need install helper on every reboot. Weird! Never got this bug before AlDente 1.20. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> Hi @papas68, Do I understand correctly that you could fix the issue as well? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

That's unexpected, thank you for sharing and we will investigate further.

**Comment by taylor325** [comment] 2023-03-13 22:11
After several reboot I have this bug again :( 
<img width="259" alt="Screenshot 2023-03-13 at 23 07 48" src="https://user-images.githubusercontent.com/52882397/224843228-2f6bf794-ac0d-4cc9-aba1-5d8ac5501880.png">
Asks for reinstall helper on every reboot 🤨

**Comment by papas68** [comment] 2023-03-14 09:38
the same boring for me









aldente pro 1.21.3MacBook Pro (13-inch, M1, 2020)




| George ***@***.***  ....... |

 
 

    Στις Τρίτη 14 Μαρτίου 2023 - 12:11:39 πμ EET, ο χρήστης taylor325 ***@***.***> έγραψε:  
 
 


After several reboot I have this bug again :(

Asks for reinstall helper on every reboot 🤨
