### ISSUE TITLE
Menu Bar - icon Not visible in MacBookPro M1 ( 14inch-2021 ) due to camera area.

### ISSUE THREAD

**Issue by openui54u** [davidwernhart/AlDente-Charge-Limiter#650] opened 2022-04-08 15:11 UTC
**Describe the bug**
The icon of AlDente is not place correctly in Menu bar. There is spacing but still not visible due to to camera -area in the MacBookPro M1 ( 14"-2021 ) .

**To Reproduce**
Use a MacBookPro 14"-2021 and have AlDente active/installed.
Copy with screen copy area incl. behind the camera area and see that the icon is present but not reachable/visible: with some good guessing you can get it though....

**Expected behavior**
Expected is the icon to be visible left or right from the non-visible area.

**Screenshots**
(Internal) screen copy show icon behind the camera-nodge
<img width="427" alt="image" src="https://user-images.githubusercontent.com/24986693/162469663-4005e081-3b76-4ac8-9788-96e4d6a87789.png">

Ext.Camera screenphoto showing camera-nodge:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/24986693/162470799-21483bcd-0039-483a-9745-2a024bf1845c.png">

**MacBook (please complete the following information):**
 - MacBook model MacBookPro M1 Pro 14"-2021   
 - macOS version 12.3.1 Monterey
 - AlDente Free?
 - AlDente Version 1.15.2

**Comment by nheeren** [comment] 2022-04-11 06:11
Exactly why I proposed #547

**Comment by kentzh1** [comment] 2022-04-11 16:53
bartender4 can help you

**Comment by openui54u** [comment] 2022-04-11 16:58
I tried some reinstall en restart. No luck. But inhad some old programm icons ( just upgraded to new laptop and M1 chip ) that could be removed and so after removing 2 ivons from menubar the aldente icon appeared. So no real solution but I am currently fine ...

**Comment by MatthiasKerbl** [comment] 2022-11-05 14:35
Hi @madler,

Do you still experience the AlDente icon in the middle of the menu bar with our newest version AlDente 1.19.2?

Cheers,
Matthias

**Comment by openui54u** [comment] 2022-11-05 14:47
Hi Thank you for asking.
Short: yes

I actually posponed the update few times. Just checked this respons with 1.19.1 
Than I updated.
I tested again ( adding the Siri icon to the menu bar as a test pushing AlDente off the viewable area…before)… and it still is.

To bad. This (crazy) notch in the middle is in the way 😀 of viewing ( in this case ) AlDente icon..

Thank you for your efforts. Do you think it’s something of AlDente or that the OS Monterey should fix that?

Edwin Glaser

**Comment by MatthiasKerbl** [comment] 2022-11-05 14:58
Hi @openui54u,

Thanks for the quick reply.
Could you please share a screenshot of the menubar area?
I would like to see if there is still an unusually big gap between the AlDente icon and the next icon or if it just gets pushed under the notch.

Cheers,
Matthias

**Comment by openui54u** [comment] 2022-11-05 18:34
Can tou see it? Sorry pressed semt button bedore typing explanatiin.
The aldente icon is om the left sode of the row if icons nright next to the notch as you can see.
When i i.e. add a siri icon to the menubar the aldente will be pushed under the notch.

Met vriendelijke groeten,

Edwin Glaser

Verstuurd vanaf mijn iPhone

Op 5 nov. 2022 om 15:58 heeft Matthias Kerbl ***@***.***> het volgende geschreven:

﻿

Hi @openui54u<https://github.com/openui54u>,

Thanks for the quick reply.
Could you please share a screenshot of the menubar area?
I would like to see if there is still an unusually big gap between the AlDente icon and the next icon or if it just gets pushed under the notch.

Cheers,
Matthias

**Comment by openui54u** [comment] 2022-11-05 18:39
Oh my, I typed this on my iPhone….I did not have my reading glasses on… .sorry for the typo’s Hope you understand 😀 

So: the icon of AlDente gets pushed under the notch when adding another icon in the right side ( here I do it with Siri as example )
I filmed a bit from above so you hopefully can see the black notch against the dark grey background  ( it is nighttime here, so the colors are now in Dark mode 😀   If needed to I can switch to light mode… but the idea and space is clear: I do believe with the size of icons this one extra icon should JUST have fitted next to it.. And the funny thing is…the icon does NOT appear to the left side of the notch… it s just behind it and not a bit, quite a big part. 

Edwin

**Comment by openui54u** [comment] 2022-11-05 18:40
Met vriendelijke groeten,

Edwin Glaser

Verstuurd vanaf mijn iPhone

Op 5 nov. 2022 om 19:34 heeft Edwin Glaser ***@***.***> het volgende geschreven:

﻿ Can tou see it? Sorry pressed semt button bedore typing explanatiin.
The aldente icon is om the left sode of the row if icons nright next to the notch as you can see.
When i i.e. add a siri icon to the menubar the aldente will be pushed under the notch.

Met vriendelijke groeten,

Edwin Glaser

Verstuurd vanaf mijn iPhone

Op 5 nov. 2022 om 15:58 heeft Matthias Kerbl ***@***.***> het volgende geschreven:

﻿

Hi @openui54u<https://github.com/openui54u>,

Thanks for the quick reply.
Could you please share a screenshot of the menubar area?
I would like to see if there is still an unusually big gap between the AlDente icon and the next icon or if it just gets pushed under the notch.

Cheers,
Matthias

**Comment by openui54u** [comment] 2022-11-05 18:41
Video os bouncing back. Here jsut the photo. [image0.jpeg]

Met vriendelijke groeten,

Edwin Glaser

Verstuurd vanaf mijn iPhone

Op 5 nov. 2022 om 15:58 heeft Matthias Kerbl ***@***.***> het volgende geschreven:

﻿

Hi @openui54u<https://github.com/openui54u>,

Thanks for the quick reply.
Could you please share a screenshot of the menubar area?
I would like to see if there is still an unusually big gap between the AlDente icon and the next icon or if it just gets pushed under the notch.

Cheers,
Matthias

**Comment by openui54u** [comment] 2022-11-05 18:42
[image0.jpeg][image1.jpeg]

Met vriendelijke groeten,

Edwin Glaser

Verstuurd vanaf mijn iPhone

Op 5 nov. 2022 om 15:58 heeft Matthias Kerbl ***@***.***> het volgende geschreven:

﻿

Hi @openui54u<https://github.com/openui54u>,

Thanks for the quick reply.
Could you please share a screenshot of the menubar area?
I would like to see if there is still an unusually big gap between the AlDente icon and the next icon or if it just gets pushed under the notch.

Cheers,
Matthias

**Comment by openui54u** [comment] 2022-11-06 09:23
[image0.jpeg]

Met vriendelijke groeten,

Edwin Glaser

Verstuurd vanaf mijn iPhone

Op 5 nov. 2022 om 19:34 heeft Edwin Glaser ***@***.***> het volgende geschreven:

﻿ Can tou see it? Sorry pressed semt button bedore typing explanatiin.
The aldente icon is om the left sode of the row if icons nright next to the notch as you can see.
When i i.e. add a siri icon to the menubar the aldente will be pushed under the notch.

Met vriendelijke groeten,

Edwin Glaser

Verstuurd vanaf mijn iPhone

Op 5 nov. 2022 om 15:58 heeft Matthias Kerbl ***@***.***> het volgende geschreven:

﻿

Hi @openui54u<https://github.com/openui54u>,

Thanks for the quick reply.
Could you please share a screenshot of the menubar area?
I would like to see if there is still an unusually big gap between the AlDente icon and the next icon or if it just gets pushed under the notch.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment] 2022-11-06 13:58
Hi @openui54u,

Unfortunately, I am not able to see any of the pictures/videos you shared. If you shared them as an attachment with an email, they don't show here on GitHub. Please try to upload them directly here in GitHub again so that I can assess the situation better.

Cheers,
Matthias

**Comment by openui54u** [comment] 2022-11-06 15:29
herewith

https://user-images.githubusercontent.com/24986693/200179610-e77965e2-de53-47a3-ace0-0d02a2f95ed7.mp4

![WhatsApp Image 2022-11-06 at 16 26 47 (5)](https://user-images.githubusercontent.com/24986693/200179618-6c4472ef-c03c-4d96-8276-c89455f56cfc.jpeg)
![WhatsApp Image 2022-11-06 at 16 26 47 (4)](https://user-images.githubusercontent.com/24986693/200179619-57aba020-6821-47e2-bd48-06ab3236e0ab.jpeg)
![WhatsApp Image 2022-11-06 at 16 26 47 (3)](https://user-images.githubusercontent.com/24986693/200179620-ef0dae08-69b1-4b39-9ccd-5ef5dbccf185.jpeg)
![WhatsApp Image 2022-11-06 at 16 26 47 (2)](https://user-images.githubusercontent.com/24986693/200179621-d7e3291a-b85b-4b22-bc95-b7068bc062c4.jpeg)
![WhatsApp Image 2022-11-06 at 16 26 47 (1)](https://user-images.githubusercontent.com/24986693/200179622-b89a977b-4ea2-4885-a1e1-71d5798e522f.jpeg)
![WhatsApp Image 2022-11-06 at 16 26 47](https://user-images.githubusercontent.com/24986693/200179623-a41e247a-63a9-436c-98c7-f3bd0c72cd17.jpeg)

**Comment by MatthiasKerbl** [comment] 2022-11-06 15:49
Thanks for the video and pictures.
As far as I can see, the issue is that macOS is pushing the AlDente icon behind the notch because of a lack of space next to it. This is unfortunately an issue from macOS and you can circumvent it by using a menubar icon manager such as Bartender.  I am not able to see any bug or issue coming from AlDente here.

Cheers,
Matthias

**Comment by openui54u** [comment] 2022-11-06 18:22
OK. thanks for your time. Please have a look at the icon being OVER the menu options of another program…. 😀 also Mac OS failure?

**Comment by MatthiasKerbl** [comment] 2022-11-06 19:02
> Please have a look at the icon being OVER the menu options of another program…. 😀 also Mac OS failure?

This behavior seems weird and I have never seen it before. It is hard to say if it is an AlDente, macOS, or third-party app issue. Is it only happening with one particular program?

**Comment by MatthiasKerbl** [comment] 2022-12-24 12:07
Hi @openui54u,

Since the original issue seems to be resolved, I will close this issue.
If you experience the overlayed AlDente icon regularly, please open a new issue.

Cheers,
Matthias

**Closed by MatthiasKerbl** 2022-12-24 12:07 UTC
