### ISSUE TITLE
MacBook can't sleep anymore

### ISSUE THREAD

**Issue by mvaneijgen** [davidwernhart/AlDente-Charge-Limiter#701] opened 2022-06-13 07:44 UTC
**Describe the bug**
I have my laptop plugged in most of the time while using it, but if not using it and I know I'll need it later I just close it and unplug everything. Lately when I then come back to it and open it it will boot up from start and will notify mee that my laptop shut down and if I want to reopen all the programs.

I've just completely removed AlDente and tested it again and now this never happens anymore.  

**To Reproduce**
1. Set AlDente to charge until 75 ~ 80% 
2. Close laptop unplug everything 
3. Come back later and open laptop again (maybe four hours)

**Expected behavior**
The laptop function normally and boot from sleep 

Version 12.3 (21E230)
MacBook Pro (15-inch, 2017)
Processor 3,1 GHz Quad-Core Intel Core 17
Memory 16 GB 2133 MHz LPDDR3
Graphics Radeon Pro 560 4 GB
Intel HD Graphics 630 1536 MB
AlDente Pro 1.17.1 (Settapp)

**Comment by RichieB2B** [comment] 2022-06-20 19:23
I see the same thing with my MacBookPro18,2 running macOS 12.4 running AlDente Pro 1.17.1:

1. Sailing Mode is enabled
2. Stop Charging when Sleeping is disabled
3. Disable sleep until Charge Limit is disabled
4. Unplug power cable during sailing (below charge limit, above sail limit)
5. Close lid
6. Open lid a few days later
7. Battery is almost empty

**Comment by ybhat** [comment] 2022-06-25 06:15
Same issue for me. Sleep is greyed out. Al Dente Pro. Only after removing helper I was able to sleep. I use my MBP in Clamshell mode so it's annoying to see it completely discharged every time.

**Comment by clintwood** [comment] 2022-07-21 10:42
Same issue for me - had to remove AlDente to stop this happening!

**Comment by redamancy-w** [comment] 2022-08-04 05:02
I also have this situation, I changed the version to 1.13, and reinstalled, it got better

**Comment by MatthiasKerbl** [comment] 2022-11-06 16:05
Hi @mvaneijgen,

Do you still experience this issue with our newest version AlDente 1.19.2?
We have made a bunch of changes and implemented more safety mechanisms over the last couple of versions to prevent this from happening.

Cheers,
Matthias

**Comment by mvaneijgen** [comment] 2022-11-08 08:20
Just tested it and my PC seemed to stay in sleep all night while plugged in. Going to test while not plugged in and closed later.

**Comment by MatthiasKerbl** [comment] 2022-11-09 09:04
> Sadly same issue. My laptop was about 50% charged last night and when I open it in the morning it is still charged, but I get the message "You shut down your computer because of a problem. Do you want to reopen all the programs."

That's strange. Thanks for testing it.
When you open the MacBook again in the morning, which charge level/battery percentage did you have?

**Comment by mvaneijgen** [comment] 2022-11-09 09:07
I didn't pay attention to it. Its so automatic in the morning. I'll test again tomorrow.

**Comment by mvaneijgen** [comment] 2022-11-10 08:50
My laptop was at 55% when closed and when opened in the morning 45% was left. It agin restarted my computer in between that time.

**Comment by MatthiasKerbl** [comment] 2022-11-11 10:19
> My laptop was at 55% when closed and when opened in the morning 45% was left. It agin restarted my computer in between that time.

Thanks for the details. Unfortunately, I am still not able to reproduce this behavior. Could you generate and share a debug file when this happens the next time? https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/

Cheers,
Matthias

**Comment by mvaneijgen** [comment] 2022-11-13 10:24
Here you go. I had to add .log as a file extension, others wise I couldn't share it. 

[aldentepro-debug-2022-11-13-11:20:51.pasta.log](https://github.com/davidwernhart/AlDente-Charge-Limiter/files/9996947/aldentepro-debug-2022-11-13-11.20.51.pasta.log)

**Comment by MatthiasKerbl** [comment] 2022-11-14 17:15
Hi @mvaneijgen,

Unfortunately, we could not find any abnormalities in your debug file. Most likely, because your system just restarted before you saved the debug file.
If possible, could you try to trigger this issue again but try to open your MacBook and generate a debug file after a while when it lost more battery than it should have but did not shut down yet?

Cheers,
Matthias

**Comment by mvaneijgen** [comment] 2022-11-14 17:24
I will try. I was also thinking, it only seems to happen after a really long while. If I just leave my laptop for a few hours nothing happens. Only when I leave it over night, this will happen, maybe the date flipping to a new day causes the issue? Just thinking out of the box.

**Comment by MatthiasKerbl** [comment] 2022-11-14 19:27
> I will try. I was also thinking, it only seems to happen after a really long while. If I just leave my laptop for a few hours nothing happens. Only when I leave it over night, this will happen, maybe the date flipping to a new day causes the issue? Just thinking out of the box.

Thanks. Theoretically possible but unlikely.

**Comment by MatthiasKerbl** [comment] 2022-12-24 11:58
Hi @mvaneijgen,

Do you have any new updates about this issue or have you tried my suggestion from above?

Cheers,
Matthias

**Comment by mvaneijgen** [comment] 2022-12-24 15:42
I went down a other rabbit hole, where I thought Better Touch tool was the culprit. https://community.folivora.ai/t/macbook-crashes-while-sleeping/29463/11 It seems to only happen when that app is on, but I'm still testing. 

[aldentepro-debug-2022-12-24-16:39:20.pasta.log](https://github.com/davidwernhart/AlDente-Charge-Limiter/files/10298830/aldentepro-debug-2022-12-24-16.39.20.pasta.log)

**Comment by MatthiasKerbl** [comment] 2022-12-26 17:55
> I went down a other rabbit hole, where I thought Better Touch tool was the culprit. https://community.folivora.ai/t/macbook-crashes-while-sleeping/29463/11 It seems to only happen when that app is on, but I'm still testing.
> 
> [aldentepro-debug-2022-12-24-16:39:20.pasta.log](https://github.com/davidwernhart/AlDente-Charge-Limiter/files/10298830/aldentepro-debug-2022-12-24-16.39.20.pasta.log)

Interesting, keep me updated if you find out anything new.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment] 2023-03-21 19:03
Hi @mvaneijgen,

Do you have any updates about this issue? 

Cheers,
Matthias

**Comment by mvaneijgen** [comment] 2023-03-21 19:47
I do not. Upgraded to a new laptop M2 and now every works as expected

**Comment by MatthiasKerbl** [comment] 2023-03-21 20:05
> I do not. Upgraded to a new laptop M2 and now every works as expected

Sounds good.
Then I will close this issue.

Cheers,
Matthias

**Closed by MatthiasKerbl** 2023-03-21 20:05 UTC
